os: windows
language: bash
jobs:
  include:
    - stage: build
      script:
        - choco install visualstudio2019buildtools
        - choco install visualstudio2019-workload-manageddesktop
        - cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
        - dir
        - .\MSBuild.exe Hto3.WindowsServiceJumpStart.sln