name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Main Project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - run: MSBuild.exe -p:Configuration=Release Hto3.WindowsServiceJumpStart\Hto3.WindowsServiceJumpStart.csproj
  build-test-project:
    name: Build Test Project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - run: MSBuild.exe -p:Configuration=Release Hto3.WindowsServiceJumpStart.Test\Hto3.WindowsServiceJumpStart.Test.csproj
  publish:
    name: Nuget Publish
    runs-on: windows-latest
    needs: [build, build-test-project]
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - run: MSBuild.exe -p:Configuration=Release Hto3.WindowsServiceJumpStart\Hto3.WindowsServiceJumpStart.csproj
      - run: nuget.exe pack Hto3.WindowsServiceJumpStart\Hto3.WindowsServiceJumpStart.csproj -Properties Configuration=Release
      - run: nuget.exe push Hto3.WindowsServiceJumpStart\*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate